apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: wordpress-mysql
description: Wordpress MySQL Deployment using gcePersistentDisk
packages:
  - ../wordpress/gcePersistentDisk/
  - ../mysql/gcePersistentDisk/
patches:
  - ../emptyDir/patch.yaml
